  - label: ":android:-:six::six:-RN_66_android"
    command:
      - "nvm install"
      - "JAVA_HOME=/usr/local/opt/openjdk@11/ ./scripts/ci.android.sh"
      - "./scripts/upload_artifact.sh"
    env:
      REACT_NATIVE_VERSION: 0.66.1
      DETOX_DISABLE_POD_INSTALL: true
      DETOX_DISABLE_POSTINSTALL: true
      SKIP_UNIT_TESTS: true
    artifact_paths:
      - "/Users/builder/work/coverage/**/*.lcov"
      - "/Users/builder/work/artifacts*.tar.gz"
